### ISSUE TITLE
Feature: Allow ensure command to take a config name to ensure

### ISSUE THREAD

**Issue by Kellel** [cloudflare/certmgr#22]
```
user@box:~$ ls /etc/certmgr.d/
certmgr-foo.json certmgr-bar.json
user@box:~$ certmgr ensure foo
```

**Comment by Kellel** [comment]
I would like to be able to ensure that the certs are setup for my service foo even if the config for the bar service is somehow broken

**Comment by ferringb** [comment]
You can abuse -d to pass the exact file you want to work on.

**Comment by ferringb** [comment]
closing this; documentation was updated to detail that you can (ab)use -d for this.
