### ISSUE TITLE
SwissSign certificate filenames contain ':' character

### ISSUE THREAD

**Issue by kyanha** [cloudflare/certmgr#37]
The SwissSign certificate filenames contain the ':' character, which prevents the checkout from succeeding on Windows systems.

**Comment by ferringb** [comment]
This isn't an issue in certmgr as much in it's cfssl_trust dependency- https://github.com/cloudflare/cfssl_trust/issues/72 tracks this on that end.

Closing this meanwhile; can reopen if/when cfssl_trust fixes it.
