### ISSUE TITLE
should include instructions for starting cfssl serve

### ISSUE THREAD

**Issue by terinjokes** [cloudflare/certmgr#8]
It's clear from the readme that this is meant to be used with cfssl. We should have a quick note for someone new who to startup cfssl's API in a way that has reasonable defaults: ie, requires an auth_key and knows about profiles.

**Comment by kisom** [comment]
This is really only useful for people already using cfssl, so it's assumed people already know about it.

**Comment by terinjokes** [comment]
@kisom Let's put it another way. *I'm* using it and don't know, I look at `cfssl serve -h` and it's not clear.

**Comment by kisom** [comment]
That's probably an issue for the cfssl repo, I think.

**Comment by terinjokes** [comment]
I'll reopen it there.

**Comment by kisom** [comment]
Thanks!
