### ISSUE TITLE
certmgr should refresh the certificaficates if the spec changes

### ISSUE THREAD

**Issue by dqminh** [cloudflare/certmgr#9]
How to reproduce:
- update the spec after the certificate has been issued

What to expect:
- the certificate is regenerated with the new spec

Maybe comparing utime of the spec or certificate, or even having a method to force regeneration of a certificate ( so we can call it whenever the spec is changed ) would help.

**Comment by kisom** [comment]
Fixed by #10, and will go out in release 1.1.0.
